language: generic

matrix:
  include:
    - os: linux

      dist: bionic
      sudo: required
      install:
        - wget https://github.com/charles32110/SVF-Static-Lib/releases/download/V1.0.1/V1.0.1.tar.gz
        - tar -xzxf V1.0.1.tar.gz
    - os: osx
      osx_image: xcode7.2


before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update       ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake gcc g++; fi

script: